import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ContextProvider from "./components/contextprovider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Techwiz Solution",
  description: "Generated by create next app",
};

// Wrap everything in ContextProvider
export default function RootLayout({ children }) {
  return (
    <html lang="en">
       <meta name="robots" content="noindex, nofollow" />
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ContextProvider>
          {children}
        </ContextProvider>
      </body>
    </html>
  );
}
